### PR TITLE
Larger touch target for back button in Toolbar on Android

### LINKED ISSUE #413: Android - Increase back button size / touch target - How it works
Screen Shot 2020-07-04 at 11 11 54 AM

### PR DESCRIPTION
**Pull request by nickmly**
Screenshot_1593883104
Fixes #413

### CODE REVIEW

**Comment by timarney** [comment]
@nickmly can you drop a screenshot into the comment above?

**Comment by nickmly** [comment]
@timarney Updated the comment. The button is the same size but the target is larger. I can also update the button size if needed.

**Comment by emilykuret** [comment]
Thinking we need to update the button size. On my Pixel XL it's quite small. Google Suggested min. 48 pixels if I remember correctly.

**Comment by nickmly** [comment]
Updated to be 48px in size: 
Screenshot_1593884733

**Comment by timarney** [comment]
@emilykuret ☝️ see button above and comment.

**Comment by emilykuret** [comment]
There seems to be a missing pixel in the arrow - but the size looks good. thank you!

**Comment by timarney** [comment]
Okay going to merge this as is as it covers the original ask.

Additional issues should be open pending direction on 

1) Should it be text?
https://github.com/cds-snc/covid-shield-mobile/issues/250

2) If not - fix the back arrow icon so it can be bigger.

**Pull request merged**
