### PR TITLE
Onboarding accessibility

### PR DESCRIPTION
**Pull request by nickmly**
Fixes the following issues: #304 #317 #337 

The onboarding screen is now accessible using a screen reader from end to end. Tested on Android using Talkback.

Changes:
- Switched off of `Carousel` component to `FlatList` (had many issues with performance and accessibility with the Carousel)
- Moved the pagination and next button to the `renderItem` callback so that screen readers will read them out
- Fixed screen readers getting stuck on steps that had `BulletPoint` components in them

### CODE REVIEW

**Comment by smcmurtry** [comment]
I just had a thought - this carousel stuff is complicated and I don't think it's actually doing anything for us at this point. 

What if we just use pages here? Every onboarding step becomes its own page inside the `<OnboardingStack.Navigator>`. We are not using modal style navigation for the onboarding navigator, we are using regular navigation with a fade transition: https://github.com/cds-snc/covid-shield-mobile/blob/master/src/navigation/MainNavigator.tsx#L73. So I don't think those transitions would be much different from the carousel.

**Comment by timarney** [comment]
@smcmurtry @nickmly - noting the solution will need to work for onboarding and how it works.

**Comment by JuliannaR** [comment]
@smcmurtry regular nav could work. There are issues on most pages that require scrolling at the moment.

**Comment by smcmurtry** [comment]
Closing in favour of #385, #398

**Pull request closed without merging**
