### PR TITLE
Landscape issues with talkback

### LINKED ISSUE #704: Talkback related issues for landscape
Focus goes to top of the page after going through "Learn more about how it works" screens AND "The app will now ask your permission" screen
https://github.com/cds-snc/covid-shield-mobile/issues/689

Focus doesn't go to heading in landscape orientation #675
https://github.com/cds-snc/covid-shield-mobile/issues/675

### PR DESCRIPTION
**Pull request by nickmly**
Fixes #704 

- When clicking 'Learn more about how it works' button in Step 3 of Onboarding and then closing that screen, focus will be directed at the button, rather than the top of the screen (step indicator)
- Same thing for Step 5 with the 'Learn more about privacy' button

Tested on Android with Talkback using portrait and landscape modes.

 **Note: needs to be tested on iOS with VoiceOver**

### CODE REVIEW

**Comment by smcmurtry** [comment]
I will test this on iOS.

**Comment by mtropper** [comment]
Works beautifully with Android, unfortunately the IOS version is still broken.

**Comment by mtropper** [comment]
@nickmly @smcmurtry @JuliannaR I modified the Navigation stack so it checks for Platform and provides a different Navigation stack based on platform. This seems to have fixed the problem

**Comment by mtropper** [comment]
Looks like merging master broke things

**Comment by mtropper** [comment]
Reverted my changes since it created some sort of conflict with recent changes in Master

**Comment by timarney** [comment]
Using this for the next build.
https://github.com/cds-snc/covid-shield-mobile/pull/827

**Comment by nickmly** [comment]
Closing in favor of #825

**Pull request closed without merging**
