### PR TITLE
Update privacypolicy.js

### PR DESCRIPTION
**Pull request by katewilhelm**
Added contact info and other minor text changes. Is it possible to make the email address a mailto type of link within an app? If so, would love some dev attention on this to do it. Tagging @EliseKa for French

### CODE REVIEW

**Comment by katewilhelm** [comment]
@lchski needs to quality check before this is merged

**Comment by timarney** [comment]
We can adjust further as needed.

**Comment by lchski** [comment]
Thanks @timarney. Sorry I haven't followed up here, it's been a day of fires. There are some more minor tweaks, and we still need to bring in the French changes. Should I reopen this PR or make a new one?

**Comment by EliseKa** [comment]
@lchski If I may, French changes are in [this PR](https://github.com/cds-snc/covid-shield-mobile/pull/751) 
We can reopen that one as well if you have new edits

**Comment by lchski** [comment]
Oops @EliseKa, apologies for that. I'll make a new PR that brings together the EN and FR changes, if any.

**Pull request merged**
