### PR TITLE
Typography and spacing

### PR DESCRIPTION
**Pull request by amazingphilippe**
This PR brings a lot of small tweaks in terms of typography, spacing, styles, colors, layout.

## General
- Default type size is 18 points across the app. We still have a `smallText` variant at 16
- Added a medium title size for the settings page. 23 points
- Large title size is ~~27~~ also 23 after all
- Changes were made in components to assign proper styles to menu items
- removed unnecessary Box nesting in ButtonSingleLine
- `lastItem` on Menu Item components can be undefined. Cleaner code.
- removed unnecessary Box nesting in StatusHeaderView
- Tweaked selection menus to display rounded corners properly
- Link color, success green colors were changed to match figma. And also meet contrast requirements
- Added info-100 color for buttons across the app
- reduced icon size from 150 to 120

## Onboarding
- Horizontal spacing on onboarding set to `m`
- bulletX and BulletCheckmark spacing
- rounded bulletX

## Settings pages with content
- Title moved from toolbar to content area. Checked with talkback. We still have the correct accessibilityRole of a header

### CODE REVIEW

**Comment by amazingphilippe** [comment]
> Noticed that a couple of the buttons have text colour issues:
> Similar issue on the diagnosed/upload screen.

Fixed in 11a1bc7

**Comment by timarney** [comment]
Pre 11a1bc7

Noting this for tracking:

**Comment by timarney** [comment]
**Regression**

**Comment by timarney** [comment]
Smaller PRs

i.e. 
PRs 
- Button updates
- Text updates 
- Section updates

Makes it easier to review + to get the updates in.

https://www.netlify.com/blog/2020/03/31/how-to-scope-down-prs/

**Comment by amazingphilippe** [comment]
Definitely a bad habit of mine. Will do

**Pull request merged**
