### PR TITLE
maximize width in landscape issue#674

### PR DESCRIPTION
**Pull request by mtropper**
#674 Some area not scroll-able in landscape on iOS and Android #674

### CODE REVIEW

**Comment by mtropper** [comment]
@JuliannaR @timarney I've made it so the screen is full screen in both orientations

**Comment by mtropper** [comment]
@JuliannaR I also fixed the Bug @srepussard was having with the rotation lock

**Comment by srepussard** [comment]
> This looks like it works well.

It is still a bug for me on Android (v49) : 
- phone rotation lock is on
- but when I rotate the phone when in the app, the screen rotates

**Comment by mtropper** [comment]
@srepussard it hasn't been merged yet. So not available on releases yet

**Comment by timarney** [comment]
@mtropper nicely done 👍

**Pull request merged**
