### PR TITLE
Change initial notifications status on Android.

### PR DESCRIPTION
**Pull request by jeberhardt**

### CODE REVIEW

**Comment by timarney** [comment]
App Covid Alert 

Status says: **OFF**



<hr>

App Covid Alert 

Status says: **OFF**



<hr>

Settings App Covid Alert 

Status says:  **ON**



Possibly different on the Play Store 

@henrytao-me thoughts on this PR?

**Comment by jeberhardt** [comment]
If I'm interpreting this issue correctly, here's a screenshot of the "Notifications" status that isn't showing up on Android. This is a screenshot taken with this PR applied. 

Screenshot_20200705-184118

**Comment by timarney** [comment]
So I think it's Push Notifications and EN notifications are off.

Either way we should be a side by side comparison. 

From the issue:

Verify that the menu displays the following messages:
EN: COVID Alert is OFF and Notifications are OFF
FR: Alerte COVID est désactivé and Notifications désactivées

iPhone displays both messages
Android does not

We could side load the app - "fresh install" and do the same actions to compare the results.

**Comment by timarney** [comment]
This other issue is part of this entire flow as well.

https://github.com/cds-snc/covid-shield-mobile/issues/271

**Comment by timarney** [comment]
Okay - I think @smcmurtry did some code around this as well that never got into the app.

Given whatever we do will effect both devices - 

A) @smcmurtry 

Seems like this would be a better initial state

```javascript
const [status, setStatus] = useState<NotificationPermissionStatusContextProps['status']>('blocked');
```

If yes let's merged this and see if the the testers do a side by side comparison.  From a fresh install - on the current Play Store + TestFlight App.

I would like to see if taking the same actions - on each device ends up giving the same results.  Paying particular attention to the order in which things are done.

Reason if we're changing the code here it won't just be for Android.

We also need to fix this one which relies on the status as well.

https://github.com/cds-snc/covid-shield-mobile/issues/271

**Comment by smcmurtry** [comment]
@timarney and I had a chat about this and I think the issue #257 that this is addressing was already fixed in an unrelated PR. Although there are some other issues with the message not updating after a change on the app settings screen that still need to be addressed.

**Pull request closed without merging**
